In [59]:
import tweepy
import numpy as np
import pandas as pd
import time
import re
import statistics

In [7]:
CONSUMER_KEY = 'pBVHBFfc7Wb6BplJXAnSIWU10'
CONSUMER_TOKEN = 'bE9b3g4m8J3ul5nloDhII5kpWnLxNH6Gqy0Rd7IpR51JQ4qq1E'

ACCESS_KEY = '471369623-JSGbfk2TNoGRFvo8NWEMd8mfjuNAswayIixX5MtF'
ACCESS_TOKEN = 'WsD9nrUnCXZogUHdHiMIhMOyy4qutSN5IWNfO8kVVBSn7'

auth = tweepy.OAuthHandler(CONSUMER_KEY, CONSUMER_TOKEN)
auth.set_access_token(ACCESS_KEY, ACCESS_TOKEN)
api = tweepy.API(auth)

In [40]:
keywords = ''
tweets = tweepy.Cursor(api.search_tweets, q=keywords, tweet_mode='extended', lang='es', geocode='-35.6751,-71.5430,300km', count=200).items()
#number_of_tweets = 0
#count = 0
tweet = list()
tweet_id = list()
created_at = list()
user_id = list()
coordinates = list()
location = list()
count = 0
for i in tweets:
    if str(i._json['coordinates']!='nan'):
        print(i._json['coordinates'][])
        break
    #tweet.append(i._json['full_text'])
    #tweet_id.append(i._json['id'])
    #created_at.append(i._json['created_at'])
    #user_id.append(i._json['user']['id'])
    #coordinates.append(i._json['coordinates'])
    #location.append(i._json['user']['location'])
    #count+=1
    #if (count==2499):
    #    break
    #break

AttributeError: 'NoneType' object has no attribute 'keys'

In [15]:
df = pd.DataFrame(zip(tweet,tweet_id, user_id, created_at,coordinates, location), columns=['tweets','tweet_id','user_id','created_at','coordinates','location'])

In [16]:
df

,tweets,tweet_id,user_id,created_at,coordinates,location
0,@IrnerioV @CATA_a_secas @UTHAconcepcion @Cambi...,1536256611412500480,180662587,Mon Jun 13 07:58:13 +0000 2022,None,Vi침a del Mar
1,Sismo: Fecha: 03:54 13/06/22 Lugar: 7 km al NO...,1536256588926832640,119565665,Mon Jun 13 07:58:07 +0000 2022,None,"Concepcion, Chile"
2,Como en Rumania pues 游놓游놓游놓游놓 https://t.co/Jukcn6HQ5A,1536256471742152704,418393159,Mon Jun 13 07:57:39 +0000 2022,None,"Santiago, Chile"
3,@aranis_andres Como lo dijo el Chicho: Anda a ...,1536256443615088640,1499912844703264770,Mon Jun 13 07:57:33 +0000 2022,None,"Santiago, Chile"
4,13-06-1967 La Universidad Cat칩lica de Valpara...,1536256340796088321,67387691,Mon Jun 13 07:57:08 +0000 2022,None,"Santiago, Chile"
...,...,...,...,...,...,...
2494,Agradecida y agradecer,1536217901652275201,941553410,Mon Jun 13 05:24:23 +0000 2022,None,"Stgo, Chile"
2495,"Ver a @DefLeppard en el top 10 en 2022, entre ...",1536217897684680711,411174596,Mon Jun 13 05:24:23 +0000 2022,None,Santiago
2496,@bernygodoy 5 ....votantes m치s por el Rechazo!!,1536217887261700097,1523232580409053184,Mon Jun 13 05:24:20 +0000 2022,None,"Algarrobo, Chile"
2497,@BancoEstado ayer Domingo 12/06 realic칠 la com...,1536217869062643712,82499709,Mon Jun 13 05:24:16 +0000 2022,None,"Santiago, Chile"
2498,@Patipelado21 @nonaossandon @HeliaMolina_M Yaa...,1536217868760653824,1223295489690537986,Mon Jun 13 05:24:16 +0000 2022,None,Santiago

In [ ]:
def remove_emojis(data):
    emoj = re.compile("["
        u"\U0001F600-\U0001F64F"  # emoticons
        u"\U0001F300-\U0001F5FF"  # symbols & pictographs
        u"\U0001F680-\U0001F6FF"  # transport & map symbols
        u"\U0001F1E0-\U0001F1FF"  # flags (iOS)
        u"\U00002500-\U00002BEF"  # chinese char
        u"\U00002702-\U000027B0"
        u"\U00002702-\U000027B0"
        u"\U000024C2-\U0001F251"
        u"\U0001f926-\U0001f937"
        u"\U00010000-\U0010ffff"
        u"\u2640-\u2642" 
        u"\u2600-\u2B55"
        u"\u200d"
        u"\u23cf"
        u"\u23e9"
        u"\u231a"
        u"\ufe0f"  # dingbats
        u"\u3030"
                      "]+", re.UNICODE)
    return re.sub(emoj, '', data)

In [20]:
word_count = list()
for i in tweet:
    words = i.split()
    word_count.append(len(words))

In [61]:
statistics.median(word_count)

13

In [25]:
df = pd.read_csv('tweets_Argentina.csv', sep='\t')

In [26]:
df

,tweets,tweet_id,user_id,coordinates,location
0,realmente los yankees piensan que la soluci칩n ...,1.533585e+18,3.167576e+08,NaN,"Santa Rosa, Argentina"
1,@marianofaridphd Y luego te imagino tooda rega...,1.533585e+18,5.776979e+07,NaN,Mar del Plata
2,@___bruja11 @MartinAlsina Anda a agitar paragu...,1.533585e+18,1.073735e+18,NaN,Mar del Plata
3,Somos desconocidos con recuerdos en com칰n,1.533585e+18,2.320139e+09,NaN,"Neuqu칠n, Argentina"
4,@marquiitoslopez Jajajajaajja,1.533585e+18,7.161094e+17,NaN,"Mar del Plata, Argentina"
...,...,...,...,...,...
199998,Ma침ana ya es s치bado y todav칤a nose si puedo ju...,1.532740e+18,2.766294e+09,NaN,Coronel Su치rez
199999,@Intrusos Hola intrusos!!!!,1.532740e+18,2.202075e+08,NaN,saturno
200000,bueno hoy me levante y eleg칤 el camino de la t...,1.532740e+18,8.402504e+17,NaN,"9 De Julio, Buenos Aires"
200001,@emakant @gramendiburo no pueden ...tranqui..s...,1.532740e+18,1.289336e+18,NaN,Mar del Plata
200002,Que frustraci칩n es ver que no te salga lo que ...,1.532740e+18,1.003313e+18,NaN,"Olavarr칤a, Argentina"